name: OreTechMines
version: $version$
main: com.koletar.jj.mineresetlite.MineResetLite
author: _OutdatedPixel
description: A lightweight solution for Mine management.
softdepend: [WorldEdit, Multiverse-Core]
commands:
  mineresetlite:
    aliases: [mrl, mr, mine, minereset]
    description: Manage mines.